package org.openmultitrack.sessionio.session

import java.io.File
import kotlin.math.roundToInt

/**
 * Reads and writes standard CUE sheet track index markers for a session directory.
 * Track titles and INDEX 01 timestamps map to [SessionTrackmark] entries.
 */
object SessionCueFile {
    const val CUE_FILE_NAME = "session.cue"

    fun cueFile(sessionDir: File): File = File(sessionDir, CUE_FILE_NAME)

    fun read(sessionDir: File): List<SessionTrackmark> {
        val file = cueFile(sessionDir)
        if (!file.isFile) return emptyList()
        return parse(file.readText())
    }

    fun write(sessionDir: File, trackmarks: List<SessionTrackmark>, audioFileName: String) {
        val sorted = trackmarks.sortedBy { it.startSec }
        val body = buildString {
            appendLine("REM Generated by OpenMultiTrack")
            appendLine("FILE \"${escapeCue(audioFileName)}\" WAVE")
            sorted.forEach { mark ->
                appendLine("  TRACK ${mark.index.toString().padStart(2, '0')} AUDIO")
                appendLine("    TITLE \"${escapeCue(mark.title)}\"")
                appendLine("    INDEX 01 ${formatCueTime(mark.startSec)}")
            }
        }
        cueFile(sessionDir).writeText(body)
    }

    internal fun parse(text: String): List<SessionTrackmark> {
        val marks = mutableListOf<SessionTrackmark>()
        var currentIndex = 0
        var currentTitle: String? = null
        text.lineSequence().forEach { raw ->
            val line = raw.trim()
            when {
                line.startsWith("TRACK ", ignoreCase = true) -> {
                    currentIndex = line.substringAfter("TRACK ").trim()
                        .substringBefore(' ')
                        .toIntOrNull() ?: marks.size + 1
                    currentTitle = null
                }
                line.startsWith("TITLE ", ignoreCase = true) -> {
                    currentTitle = unquote(line.substringAfter("TITLE ").trim())
                }
                line.startsWith("INDEX 01 ", ignoreCase = true) -> {
                    val time = line.substringAfter("INDEX 01 ").trim()
                    val startSec = parseCueTime(time)
                    val title = currentTitle?.takeIf { it.isNotBlank() }
                        ?: "Track ${currentIndex.toString().padStart(2, '0')}"
                    marks += SessionTrackmark(
                        index = currentIndex.coerceAtLeast(1),
                        title = title,
                        startSec = startSec,
                    )
                }
            }
        }
        return marks.sortedBy { it.startSec }
    }

    internal fun formatCueTime(sec: Float): String {
        val totalCs = (sec.coerceAtLeast(0f) * 100f).roundToInt()
        val hours = totalCs / 360_000
        val minutes = (totalCs % 360_000) / 6_000
        val seconds = (totalCs % 6_000) / 100
        val frames = ((totalCs % 100) * 75 + 50) / 100
        return if (hours > 0) {
            "%d:%02d:%02d:%02d".format(hours, minutes, seconds, frames.coerceIn(0, 74))
        } else {
            "%02d:%02d:%02d".format(minutes, seconds, frames.coerceIn(0, 74))
        }
    }

    internal fun parseCueTime(raw: String): Float {
        val parts = raw.trim().split(':')
        return when (parts.size) {
            4 -> {
                val h = parts[0].toIntOrNull() ?: 0
                val m = parts[1].toIntOrNull() ?: 0
                val s = parts[2].toIntOrNull() ?: 0
                val f = parts[3].toIntOrNull() ?: 0
                h * 3600f + m * 60f + s + f / 75f
            }
            3 -> {
                val m = parts[0].toIntOrNull() ?: 0
                val s = parts[1].toIntOrNull() ?: 0
                val f = parts[2].toIntOrNull() ?: 0
                m * 60f + s + f / 75f
            }
            2 -> {
                val m = parts[0].toIntOrNull() ?: 0
                val s = parts[1].toIntOrNull() ?: 0
                m * 60f + s
            }
            else -> 0f
        }
    }

    /** Parse user-entered timestamps such as `1:23`, `01:02:03`, or `45.5`. */
    fun parseUserTimestamp(input: String): Float? {
        val trimmed = input.trim()
        if (trimmed.isEmpty()) return null
        trimmed.toFloatOrNull()?.let { return it.coerceAtLeast(0f) }
        if (':' in trimmed) return parseCueTime(trimmed)
        return null
    }

    fun formatUserTimestamp(sec: Float): String = formatTransportTimeForCue(sec)

    private fun formatTransportTimeForCue(sec: Float): String {
        val total = sec.coerceAtLeast(0f).roundToInt()
        val hours = total / 3600
        val minutes = (total % 3600) / 60
        val seconds = total % 60
        return if (hours > 0) {
            "%d:%02d:%02d".format(hours, minutes, seconds)
        } else {
            "%d:%02d".format(minutes, seconds)
        }
    }

    fun preferredAudioFileName(sessionDir: File, metadata: SessionMetadata?): String {
        metadata?.channels?.firstOrNull()?.fileName?.let { return it }
        return sessionDir.listFiles()
            ?.firstOrNull { it.isFile && it.extension.equals("wav", ignoreCase = true) }
            ?.name
            ?: "mix.wav"
    }

    private fun escapeCue(value: String): String =
        value.replace("\\", "\\\\").replace("\"", "\\\"")

    private fun unquote(value: String): String {
        val trimmed = value.trim()
        if (trimmed.startsWith('"') && trimmed.endsWith('"') && trimmed.length >= 2) {
            return trimmed.substring(1, trimmed.length - 1)
                .replace("\\\"", "\"")
                .replace("\\\\", "\\")
        }
        return trimmed
    }
}
